### Find all users with a given email
GET http://localhost:3000/auth?

### Find a particular user with given ID
GET http://localhost:3000/auth/1

### Sign In
POST http://localhost:3000/auth/signin
content-type: application/json

{
	"email": "test@test.com",
	"password": "test"
}

### Sign Out
POST http://localhost:3000/auth/signout


### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
	"email": "test1@test.com",
	"password": "test"
}

### Update user
PATCH http://localhost:3000/auth /1
content-type: application/json

{
	"email": "kral@example.com",
	"password":"1234"
}

### Delete user
DELETE http://localhost:3000/auth/1


### Who am I?
GET http://localhost:3000/auth/whoami
